---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2022/7/25 23:38
---


local s = require("Common/String")

__G__RoleDataTable = __G__RoleDataTable or {}

__G__RoleDataTable.DataTable = {}

function __G__RoleDataTable.save_data()
    local mysql = require("luasql.mysql").mysql()
    local db_define = require("ServerDB/ServerDBDefine")
    local con = mysql:connect("roledata", db_define.User, db_define.Password, db_define.Host, db_define.Port)
    for role_id, role in pairs(__G__RoleDataTable.DataTable) do
        role_name = role:GetRoleName()
        int_table = role.IntTable
        obj_table = role.ObjTable
        serialize_int = s.Serialize(int_table)
        serialize_obj = s.Serialize(obj_table)
        local cur = con:execute(string.format("INSERT INTO roledata
        (role_id, role_name, int_table, obj_table)
        values (%s, '%s', '%s', '%s') ON DUPLICATE KEY
        UPDATE role_id = %s, role_name = '%s', int_table='%s', obj_table='%s';",
                role_id, role_name, serialize_int, serialize_obj,
                role_id, role_name, serialize_int, serialize_obj
        ))
    end
end

function __G__RoleDataTable.load_data()
    --TODO
    -- TODO 读取mysql的角色数据，数据库部分肯定要逻辑分离，从Logic的Server拆分，拆分到ServerDB中
    local mysql = require("luasql.mysql").mysql()
    local db_define = require("ServerDB/ServerDBDefine")
    local con = mysql:connect("world", db_define.User, db_define.Password, db_define.Host, db_define.Port)
    local cur = con:execute("select role_id, role_name, int_table, obj_table roledata;")
    local row = cur:fetch({}, "a")
    while row do
        __G__PersistentDataTable.DataTable[row.name] = s.unSerialize(row.data)
        row = cur:fetch(row,"a")
    end
end

return __G__RoleDataTable